# Generated by Django 5.2.7 on 2025-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('password', models.CharField(default='Access@123', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('managed_by', models.CharField(default='', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
