# Generated by Django 5.2.7 on 2025-11-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='clientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
    ]
