# Generated by Django 5.2.7 on 2025-11-04 16:30

from django.db import migrations, models


def delete_existing_notes(apps, schema_editor):
    """Delete all existing notes before changing ID field type"""
    Note = apps.get_model('api', 'Note')
    Note.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_note_clientid'),
    ]

    operations = [
        migrations.RunPython(delete_existing_notes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
