# Generated by Django 5.2.7 on 2025-11-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
