# Generated by Django 5.2.7 on 2025-11-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_note_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='', max_length=50)),
                ('messageId', models.CharField(default='', max_length=12)),
                ('transactionId', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
