# Generated by Django 5.2.7 on 2025-11-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_django_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
