# Generated by Django 5.2.7 on 2025-11-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_client_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
