# Generated by Django 5.2.7 on 2025-11-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userdetails_is_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='is_leader',
        ),
    ]
