# Generated by Django 5.2.7 on 2025-11-10 17:19

from django.db import migrations
import uuid


def migrate_existing_team_members(apps, schema_editor):
    """Migrate existing UserDetails.team relationships to TeamMember"""
    UserDetails = apps.get_model('api', 'UserDetails')
    TeamMember = apps.get_model('api', 'TeamMember')
    
    # Get all UserDetails that have a team
    user_details_with_teams = UserDetails.objects.filter(team__isnull=False)
    
    for user_detail in user_details_with_teams:
        # Check if TeamMember already exists
        if not TeamMember.objects.filter(user=user_detail, team=user_detail.team).exists():
            # Generate TeamMember ID
            team_member_id = uuid.uuid4().hex[:12]
            while TeamMember.objects.filter(id=team_member_id).exists():
                team_member_id = uuid.uuid4().hex[:12]
            
            # Create TeamMember with created_at set to user's created_at
            TeamMember.objects.create(
                id=team_member_id,
                user=user_detail,
                team=user_detail.team
            )


def reverse_migration(apps, schema_editor):
    """Reverse migration - remove TeamMember entries"""
    TeamMember = apps.get_model('api', 'TeamMember')
    TeamMember.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_teammember'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_team_members, reverse_migration),
    ]
