# Generated by Django 5.2.7 on 2025-11-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20251110_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='joined_at',
        ),
    ]
