# Generated by Django 5.2.7 on 2025-11-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_teammember_joined_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='team',
        ),
    ]
