# Generated by Django 5.2.7 on 2025-11-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_team_from_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
