# Generated by Django 5.2.7 on 2025-11-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_phone_to_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
