# Generated by Django 5.2.7 on 2025-11-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=200)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('subcategory', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAsset',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assets', to='api.asset')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assets', to='api.client')),
            ],
            options={
                'unique_together': {('client', 'asset')},
            },
        ),
    ]
