# Generated by Django 5.2.7 on 2025-11-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_asset_clientasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
