# Generated by Django 5.2.7 on 2025-11-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_asset_default_alter_asset_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientasset',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
