# Generated by Django 5.2.7 on 2025-11-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_clientasset_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='RIB',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('iban', models.CharField(blank=True, default='', max_length=34)),
                ('bic', models.CharField(blank=True, default='', max_length=11)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_holder', models.CharField(blank=True, default='', max_length=200)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.URLField(default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRIB',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ribs', to='api.client')),
                ('rib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ribs', to='api.rib')),
            ],
            options={
                'unique_together': {('client', 'rib')},
            },
        ),
        migrations.CreateModel(
            name='ClientUsefulLink',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_useful_links', to='api.client')),
                ('useful_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_useful_links', to='api.usefullink')),
            ],
            options={
                'unique_together': {('client', 'useful_link')},
            },
        ),
    ]
