# Generated by Django 5.2.7 on 2025-11-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rib_usefullink_clientrib_clientusefullink'),
    ]

    operations = [
        migrations.AddField(
            model_name='rib',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='rib',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='rib',
            name='branch_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='rib',
            name='domiciliation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rib',
            name='rib_key',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
