# Generated by Django 5.2.7 on 2025-11-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rib_account_number_rib_bank_code_rib_branch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefullink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='useful_links/'),
        ),
    ]
