# Generated by Django 5.2.7 on 2025-11-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_usefullink_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='invested_capital',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='trading_portfolio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
