# Generated by Django 5.2.7 on 2025-11-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_client_bonus_client_invested_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
