# Generated by Django 5.2.7 on 2025-11-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_client_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('bonus', 'Bonus'), ('achat', 'Achat'), ('vente', 'Vente'), ('interets', 'Intérêts'), ('frais', 'Frais'), ('investissement', 'Investissement'), ('perte', 'Perte')], default='depot', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('conteste', 'Contesté')], default='en_cours', max_length=50)),
                ('visible_by_client', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.client')),
            ],
        ),
    ]
