# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_productcategory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefullink',
            name='button',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
