# Generated by Django 5.2.7 on 2026-01-20 15:16

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_fix_ticker_symbol_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='app_settings/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='client_profiles/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='useful_links/'),
        ),
    ]
