# Generated by Django 5.2.7 on 2026-01-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_add_logo_url_to_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
