# Generated by Django 5.2.7 on 2026-01-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_add_type_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('bonus', 'Bonus'), ('achat', 'Achat'), ('vente', 'Vente'), ('interets', 'Intérêts'), ('frais', 'Frais'), ('investissement', 'Investissement'), ('transfert', 'Transfert'), ('perte', 'Perte')], default='depot', max_length=50),
        ),
    ]
