# Generated by Django 5.2.7 on 2026-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_add_subscription_fields_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_from',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_to',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
