# Generated by Django 5.2.7 on 2026-01-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_add_transfer_from_to_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('conteste', 'Contesté'), ('annule', 'Annulé')], default='en_cours', max_length=50),
        ),
    ]
