# Generated by Django 5.2.7 on 2026-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_add_annule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='trading_view_symbol',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
