# Generated by Django 5.2.7 on 2026-01-26

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_position_trade_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='login_background_image',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='app_settings/'),
        ),
    ]

