# Generated by Django 5.2.7 on 2026-01-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_appsettings_login_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='platform_name',
            field=models.CharField(default='Panorama', max_length=80),
        ),
    ]

