# Generated by Django 5.2.7 on 2026-01-26 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_appsettings_platform_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('open', 'Ouverte'), ('done', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientChatMessage',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('sender', models.CharField(default='client', max_length=10)),
                ('message', models.TextField(default='')),
                ('read_by_client', models.BooleanField(default=False)),
                ('read_by_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.client')),
                ('manager_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_client_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
