# Generated by Django 5.2.7 on 2026-01-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_position_status_clientchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='article_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='newspost',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
