# Generated by Django 5.2.7 on 2026-01-28 16:59

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_trade_conversion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='user_profiles/'),
        ),
    ]
