# Generated by Django 5.2.7 on 2026-01-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_add_payment_methods_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='period_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='period_index',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
