# Generated by Django 5.2.7 on 2026-01-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_make_position_period_fields_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
