# Generated by Django 5.2.7 on 2026-01-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_remove_price_from_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
