# Generated by Django 5.2.7 on 2026-01-29 09:52

from django.db import migrations, models


def convert_no_profitability_to_boolean(apps, schema_editor):
    """Convert 'Oui'/'Non' string values to boolean"""
    Product = apps.get_model('api', 'Product')
    for product in Product.objects.all():
        if isinstance(product.no_profitability, str):
            # 'Oui' means no profitability (True), 'Non' means has profitability (False)
            product.no_profitability = product.no_profitability.strip().lower() == 'oui'
            product.save(update_fields=['no_profitability'])


def reverse_convert_no_profitability_to_boolean(apps, schema_editor):
    """Convert boolean back to 'Oui'/'Non' string values"""
    Product = apps.get_model('api', 'Product')
    for product in Product.objects.all():
        if isinstance(product.no_profitability, bool):
            # True = 'Oui' (no profitability), False = 'Non' (has profitability)
            product.no_profitability = 'Oui' if product.no_profitability else 'Non'
            product.save(update_fields=['no_profitability'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_remove_active_from_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='no_profitability',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(convert_no_profitability_to_boolean, reverse_convert_no_profitability_to_boolean),
    ]
