# Generated by Django 5.2.7 on 2026-01-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_change_no_profitability_to_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show_min_profitability',
        ),
    ]
