# Generated by Django 5.2.7 on 2026-01-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_remove_show_min_profitability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_price_variation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='enable_price_variation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_price_variation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_price_variation',
        ),
    ]
