# Generated by Django 5.2.7 on 2026-01-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_remove_price_variation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_savings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='show_on_launch',
        ),
    ]
