# Generated by Django 5.2.7 on 2026-01-29 15:50

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_remove_is_savings_and_show_on_launch'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identity_document',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='kyc/identity/'),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='proof_of_address',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='kyc/address/'),
        ),
        migrations.AddField(
            model_name='client',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='kyc/selfie/'),
        ),
    ]
