# Generated by Django 5.2.7 on 2026-01-29 17:12

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_client_identity_document_client_kyc_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identity_document_verso',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='kyc/identity/'),
        ),
    ]
