# Generated by Django 5.2.7 on 2026-02-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_transaction_validated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClientProduct',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_products', to='api.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_products', to='api.product')),
            ],
            options={
                'unique_together': {('client', 'product')},
            },
        ),
    ]
