# Generated by Django 5.2.7 on 2026-02-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_add_default_to_product_and_client_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('online', 'En ligne'), ('away', 'Absent'), ('offline', 'Déconnecté')], default='offline', max_length=20),
        ),
    ]
