# Generated by Django 5.2.7 on 2026-02-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_add_user_status_and_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_funds',
            field=models.BooleanField(default=False),
        ),
    ]
