# Generated by Django 5.2.7 on 2026-02-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_add_available_funds_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='position_generation_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
