# Generated by Django 5.2.7 on 2026-02-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_delete_event_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='valeur_cumulee_interets',
        ),
    ]
