# Generated by Django 5.2.7 on 2026-02-03 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_remove_product_valeur_cumulee_interets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVerificationConfig',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('steps_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_configs', to='api.client')),
            ],
            options={
                'verbose_name': 'Client Verification Config',
                'verbose_name_plural': 'Client Verification Configs',
                'unique_together': {('client',)},
            },
        ),
    ]
