# Generated by Django 5.2.7 on 2026-02-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_clientverificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rib_account_holder',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='rib_account_number',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='client',
            name='rib_bank_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='client',
            name='rib_bank_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='rib_bic',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='client',
            name='rib_branch_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='client',
            name='rib_domiciliation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='rib_iban',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
        migrations.AddField(
            model_name='client',
            name='rib_key',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
