# Generated by Django 5.2.7 on 2026-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_add_client_rib_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trading_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
