# Generated by Django 5.2.7 on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_add_trading_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='website',
            field=models.URLField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
    ]
