# Generated by Django 5.2.7 on 2026-02-09 10:47

import api.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_appsettings_address_website_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('bonus', 'Bonus'), ('achat', 'Achat'), ('vente', 'Vente'), ('interets', 'Intérêts'), ('frais', 'Frais'), ('transfert', 'Transfert'), ('perte', 'Perte')], default='depot', max_length=50),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('document_type', models.CharField(choices=[('contract', 'Contrat'), ('kyc', 'Document KYC'), ('identity', "Pièce d'identité"), ('address', 'Justificatif de domicile'), ('financial', 'Document financier'), ('other', 'Autre')], default='other', max_length=50)),
                ('file', models.FileField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='client_documents/')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.client')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.transaction')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
