# Generated by Django 5.2.7 on 2026-02-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_alter_transaction_type_clientdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='support',
        ),
        migrations.RemoveField(
            model_name='client',
            name='template',
        ),
    ]
