# Generated by Django 5.2.7 on 2026-02-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_remove_template_support_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='banner_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
