# Generated by Django 5.2.7 on 2026-02-10 13:17

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_add_banner_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='app_settings/'),
        ),
    ]
