# Generated by Django 5.2.7 on 2026-02-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_appsettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_logs', to='api.client'),
        ),
        migrations.CreateModel(
            name='ClientPlatformLog',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('action_type', models.CharField(default='', max_length=100)),
                ('action_details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_logs', to='api.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
