# Generated by Django 5.2.7 on 2026-02-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_add_client_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('conteste', 'Contesté'), ('annule', 'Annulé')], default='en_cours', max_length=50),
        ),
    ]
