# Generated by Django 5.2.7 on 2026-02-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_remove_product_capitalisation_fonds'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientasset',
            name='availability_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientasset',
            name='availability_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
