# Generated by Django 5.2.7 on 2026-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_clientasset_availability_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproduct',
            name='availability_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproduct',
            name='availability_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
