# Generated by Django 5.2.7 on 2026-02-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_clientproduct_availability_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='platform_access',
        ),
    ]
