# Generated by Django 5.2.7 on 2026-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_remove_platform_access_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subscription_birth_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
