# Generated by Django 5.2.7 on 2026-02-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_alter_transaction_subscription_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subscription_city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
