# Generated by Django 5.2.7 on 2026-02-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_alter_transaction_subscription_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subscription_contract_end',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription_duration',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription_first_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription_interest_period',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription_ip',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription_last_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription_profitability',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription_signature',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
