# Generated by Django 5.2.7 on 2026-02-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_alter_transaction_subscription_contract_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source_index',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
