# Generated by Django 5.2.7 on 2026-02-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_appnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='interest_period',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='profitability_period',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
