# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_alter_product_interest_profitability_period_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract_preview_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
