# Generated by Django 5.2.7

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_add_contract_preview_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='platform_banner_image',
            field=models.ImageField(blank=True, null=True, storage=api.storage.CloudinaryMediaStorage, upload_to='app_settings/'),
        ),
    ]
