# Generated by Django 5.2.7 on 2026-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_balance_to_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='trading_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
