# Generated by Django 5.2.7 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_trading_enabled_default_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('en_cours', 'En cours'), ('en_verification', 'En vérification'), ('valide', 'Validé'), ('conteste', 'Contesté'), ('annule', 'Annulé')], default='en_cours', max_length=50),
        ),
    ]
