# Generated by Django 5.2.7 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_add_en_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar US'), ('CHF', 'Franc suisse')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('bonus', 'Bonus'), ('achat', 'Achat'), ('vente', 'Vente'), ('interets', 'Intérêts'), ('frais', 'Frais'), ('transfert', 'Transfert'), ('perte', 'Perte'), ('conversion', 'Conversion')], default='depot', max_length=50),
        ),
    ]
