# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_referralprospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_price_update_attempt',
            field=models.DateTimeField(blank=True, null=True, help_text='Last failed price update attempt. Used to avoid retrying failing assets every run.'),
        ),
    ]
