# Generated by Django 5.2.7 on 2026-04-13 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_appsettings_company_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionDeletionRecord',
            fields=[
                ('id', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('position_id', models.CharField(db_index=True, max_length=12)),
                ('client_id', models.CharField(db_index=True, max_length=12)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('product_id', models.CharField(blank=True, max_length=12, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('trigger', models.CharField(db_index=True, max_length=128)),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_deletion_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_id', '-created_at'], name='api_positio_client__8bfc12_idx')],
            },
        ),
    ]
