# Generated by Django 5.2.7 on 2026-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_clientproduct_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='last_price_update_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
