# Generated by Django 5.2.7 on 2026-05-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_appsettings_company_country_gr'),
        ('api', '0139_clientplatformlog_origin'),
    ]

    operations = [
    ]
