# Generated by Django 5.2.7 on 2026-06-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_clientchatmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referral_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_offer_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
